items:
  test_item:
    material: 'IRON_SWORD'
    displayName: '&e&lTest Item'
    lore:
      - 'This is a test item'
      - 'It has &e2 lines of lore'
    enchantments:
      sharpness: 1
    recipe:
      crafting:
        pattern:
          - 'XXX'
          - 'XYX'
          - 'XXX'
        materials:
          X: 'IRON_INGOT'
          Y: 'IRON_SWORD'
      furnace:
        input: 'IRON_SWORD'
        exp: 10
        cookTime: 20
    drops:
      mobs:
        ZOMBIE:
          chance: 10
          amount: 1
      blocks:
        IRON_BLOCK:
          chance: 10
          amount: 1
    properties:
      canBeRenamed: false
      isUnbreakable: true
  test_craft:
    material: 'BRICK'
    displayName: '&aTest Craft Result'
    recipe:
      crafting:
        pattern:
          - 'XXX'
          - '   '
          - '   '
        materials:
          X: 'custom/test_item'
    properties:
      isGlowing: true
  test_potion:
    material: POTION
    displayName: '&fTest Potion'
    effects:
      SPEED:
        level: 1
        duration: 60
    properties:
      potionColor: 255,255,255