name: MythicItems
version: ${project.version}
main: com.github.sniddunc.mythicitems.MythicItems
api-version: 1.13
load: STARTUP
authors: [sniddunc]
description: A simple to use, congfigurable custom item API
commands:
  mythicitems:
    aliases:
      - mitem